name: Construir Frontend

on:
  push:
    branches:
      - feature/devops
    paths-ignore:
      - '**.md'

jobs:
  build_frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build con Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npm run build
      
      - name: Deploy
        run: npm run deploy
